# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
env:
  DBURL: ${{vars.DBURL}}
  DBNAME: ${{vars.DBNAME}}
  TOKEN: ${{vars.TOKEN}}
  
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    
    steps:
    - uses: actions/checkout@v4
    - name: Use Nextjs build cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.npm
          ${{ github.workspace }}/.next/cache
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
        restore-keys: |
          ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npx next build
    - run: npm test

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2.5.0
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        name: id_ed25519
        known_hosts: ${{secrets.SSH_KNOWN_HOSTS}}
        config: ${{ secrets.SSH_CONFIG_YARNSCOMBE }}
    - name: Rsync .dist files
      run: rsync -r ./ sbt:QS-Next/
    - name: Build Project
      run: ssh sbt cd QS-Next/ && npm ci && npx next build
    - name: Restart Data-Server
      run: ssh sbt sudo systemctl restart next-server.service
